# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-28 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180728_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
