# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_article_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='salary',
            field=models.IntegerField(default=1258),
        ),
    ]
