# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180825_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='workers',
            name='tester_list',
            field=models.ManyToManyField(to='account.Tester'),
        ),
    ]
